---
- name: Install MariaDB server and configure
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install MariaDB server
      package:
        name: mariadb-server
        state: present

    - name: Secure MariaDB installation (set root password)
      mysql_user:
        name: root
        password: Hichem2024
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: yes
        host_all: yes

    - name: Create database for Nextcloud
      mysql_db:
        name: nextcloud
        state: present
        login_user: root
        login_password: Hichem2024

    - name: Create MySQL user for Nextcloud
      mysql_user:
        name: nextcloud_user
        password: hichem2024
        priv: 'nextcloud.*:ALL'
        host: localhost
        state: present
        login_user: root
        login_password: Hichem2024

    - name: Flush privileges
      mysql_query:
        query: FLUSH PRIVILEGES
        login_user: root
        login_password: Hichem2024

    - name: Add PPA for PHP
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Install required packages
      apt:
        name:
          - apache2
          - php8.0
          - libapache2-mod-php8.0
          - php8.0-mysql
          - php8.0-xml
          - php8.0-mbstring
          - php8.0-curl
          - php8.0-zip
          - php8.0-gd
          - php8.0-intl
          - php8.0-bcmath
          - php8.0-gmp
          - wget
          - unzip
          - git
          - make
          - python3-pymysql
        state: present

    - name: Download Nextcloud 29.0.2
      get_url:
        url: https://download.nextcloud.com/server/releases/nextcloud-29.0.2.zip
        dest: /tmp/nextcloud-29.0.2.zip

    - name: Unzip Nextcloud
      unarchive:
        src: /tmp/nextcloud-29.0.2.zip
        dest: /var/www/
        remote_src: yes

    - name: Set correct permissions on Nextcloud directory
      file:
        path: /var/www/nextcloud
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create Apache configuration for Nextcloud
      copy:
        dest: /etc/apache2/sites-available/nextcloud.conf
        content: |
          <VirtualHost *:80>
            DocumentRoot /var/www/nextcloud
            ServerName localhost

            <Directory /var/www/nextcloud/>
              Options +FollowSymlinks
              AllowOverride All
              <IfModule mod_dav.c>
                Dav off
              </IfModule>
              SetEnv HOME /var/www/nextcloud
              SetEnv HTTP_HOME /var/www/nextcloud
            </Directory>

            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Enable Nextcloud site
      command: a2ensite nextcloud.conf

    - name: Disable Apache Local config
      command: a2dissite 000-default

    - name: Enable rewrite module
      command: a2enmod rewrite

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Wait for Apache to restart
      wait_for:
        port: 80
        delay: 10

    - name: Create admin account for Nextcloud
      shell: |
        sudo -u www-data php /var/www/nextcloud/occ \
          maintenance:install \
          --database "mysql" \
          --database-name "nextcloud" \
          --database-host "localhost" \
          --database-user "nextcloud_user" \
          --database-pass "hichem2024" \
          --admin-user "admin" \
          --admin-pass "admin_password"
      args:
        executable: /bin/bash
